Wadnr: Fixing crash found by Dal:
2019-02-26 16:02:29,304;54;ERROR;LtInfo.Common.SitkaLogger;

Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at ProjectFirma.Web.Common.ToCsvListExtensions.<>c.<ToDistinctOrderedCsvList>b__1_0(ProgramIndex x) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\ProjectFirma.Web\Common\ToCsvListExtensions.cs:line 24
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.<DistinctIterator>d__64`1.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at ProjectFirma.Web.Common.ToCsvListExtensions.MakeDistinctCaseInsensitiveStringListFromObjectList[T](List`1 projectCodes, Func`2 funcObjectToString) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\ProjectFirma.Web\Common\ToCsvListExtensions.cs:line 29
   at ProjectFirma.Web.Common.ToCsvListExtensions.ToDistinctOrderedCsvList(List`1 programIndices) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\ProjectFirma.Web\Common\ToCsvListExtensions.cs:line 24
   at ASP._Page_Views_Agreement_Detail_cshtml.Execute() in c:\sitka\WADNRForestHealth\wwwroot\Views\Agreement\Detail.cshtml:line 182
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.StartPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

User: Dal Marsters
LogonName: dal.marsters@sitkatech.com
PersonID: 5273
Organization: Sitka Technology Group

IP Address: 192.168.10.98
Hostname: devrig08.sitka.local
Whois Info:
            NetRange:       192.168.0.0 - 192.168.255.255
            CIDR:           192.168.0.0/16
            NetName:        PRIVATE-ADDRESS-CBLK-RFC1918-IANA-RESERVED
            NetHandle:      NET-192-168-0-0-1
            Parent:         NET192 (NET-192-0-0-0-0)
            NetType:        IANA Special Use
            OriginAS:
            Organization:   Internet Assigned Numbers Authority (IANA)
            RegDate:        1994-03-15
            Updated:        2013-08-30
            Comment:        These addresses are in use by many millions of independently operated networks, which might be as small as a single computer connected to a home gateway, and are automatically configured in hundreds of millions of devices.  They are only intended for use within a private context  and traffic that needs to cross the Internet will need to use a different, unique address.
            Comment:
            Comment:        These addresses can be used by anyone without any need to coordinate with IANA or an Internet registry.  The traffic from these addresses does not come from ICANN or IANA.  We are not the source of activity you may see on logs or in e-mail records.  Please refer to http://www.iana.org/abuse/answers
            Comment:
            Comment:        These addresses were assigned by the IETF, the organization that develops Internet protocols, in the Best Current Practice document, RFC 1918 which can be found at:
            Comment:        http://datatracker.ietf.org/doc/rfc1918
            Ref:            https://rdap.arin.net/registry/ip/192.168.0.0
            OrgName:        Internet Assigned Numbers Authority
            OrgId:          IANA
            Address:        12025 Waterfront Drive
            Address:        Suite 300
            City:           Los Angeles
            StateProv:      CA
            PostalCode:     90292
            Country:        US
            RegDate:
            Updated:        2012-08-31
            Ref:            https://rdap.arin.net/registry/entity/IANA
            OrgTechHandle: IANA-IP-ARIN
            OrgTechName:   ICANN
            OrgTechPhone:  +1-310-301-5820
            OrgTechEmail:  abuse@iana.org
            OrgTechRef:    https://rdap.arin.net/registry/entity/IANA-IP-ARIN
            OrgAbuseHandle: IANA-IP-ARIN
            OrgAbuseName:   ICANN
            OrgAbusePhone:  +1-310-301-5820
            OrgAbuseEmail:  abuse@iana.org
            OrgAbuseRef:    https://rdap.arin.net/registry/entity/IANA-IP-ARIN

URL: https://wadnrforesthealth.qa.projectfirma.com/Agreement/AgreementDetail/116

Http Request:
GET /Agreement/AgreementDetail/116 HTTP/1.1
Cache-Control: max-age=0
Connection: close
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cookie: _ga=GA1.2.1381902122.1541114527; _gid=GA1.2.931107479.1551117278; ASP.NET_SessionId=2rc0xbgghvdbgaln4az3co3o; grid_ck_dhtmlprojectCalendarYearExpendituresForOrganizationGridfilterVisible=0; grid_ck_dhtmluserProjectListGridfilterVisible=0; grid_ck_dhtmlgrantAllocationsNoDataGridNamefilterVisible=0; grid_ck_dhtmlgrantsGridName=%7C%7C%7C%7C%7C2017%20Consolidated%20Payment%20Grant%7C%7C%7C%7C%7C; grid_ck_dhtmlUserGrid=%7C%7C%7C%7C%7C%7C%7C%7C%7C%7C%7C%7C%7C; grid_ck_dhtmlprojectUpdateBatchfilterVisible=0; grid_ck_dhtmlprojectNotificationsfilterVisible=0; .AspNet.ApplicationCookie=EADYbc2txjo6pQiY83EemT9eWeGZKr9YnJP471DrwTq_zq7n7FHTOd0feGEa5WwkVX1j-ZWPOuVJQsl3_n19AVA5vh9UA5_2IME53LW9jNfddh09sErXGp5aF6aHFYxm9PI0HSrqI3GREvhF584_cDrR7AcL5CtMCgs_Ut3U_H55PNG5Fw3konILtGpxAArvoTDEiBjVslKmR1VJbCOTkStrHLpsVwKkaQ7IQeWjnZk75fgTfprH9aG21tjIH8EO7v7yN3oBkiV4zkHhwu-vCa5RKLlIsof34ug7nexv0eZTHocbJYVRgDTr23LbcGg9GM-hOMMf8JkRCQHcjfd_F70YpHyVJH7dMDsq75LPvNP-dDMzlXIQAJfXfSFwF9YCdmXJ5Y788zyeLvqpgzz53t9S1CUj6v3heN4uxM3Oaihf1cFOj-yqZvsPKlT_r1ncsx0MYPDbi5XeeEFwNeY6mDhaYKFLMjo0dg8wSpuTP8E; gridSettingsuserAgreementsFromUserGridDivID=0-70-100-134-130-180-120-120-70|0-70-100-130-130-180-120-120-70|||; grid_ck_dhtmlgrantAllocationsGridName=%7C2012-DG-11062764-018%7C%7C%7C%7C%7C%7C%7C%7C%7C%7C%7C; grid_ck_dhtmlagreementsGridName=%7C%7C%7C%7C%7C%7CAmendment%20%231%20-%2020-Year%20Forest%20Health%20Stretegic%20Plan%20Consulting%20Services%7C%7C%7C; _gat=1
Host: wadnrforesthealth.qa.projectfirma.com
Referer: https://wadnrforesthealth.qa.projectfirma.com/Agreement/AgreementDetail/116
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36
upgrade-insecure-requests: 1

System.NullReferenceException: Object reference not set to an instance of an object.
   at ProjectFirma.Web.Common.ToCsvListExtensions.<>c.<ToDistinctOrderedCsvList>b__1_0(ProgramIndex x) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\ProjectFirma.Web\Common\ToCsvListExtensions.cs:line 24
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.<DistinctIterator>d__64`1.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at ProjectFirma.Web.Common.ToCsvListExtensions.MakeDistinctCaseInsensitiveStringListFromObjectList[T](List`1 projectCodes, Func`2 funcObjectToString) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\ProjectFirma.Web\Common\ToCsvListExtensions.cs:line 29
   at ProjectFirma.Web.Common.ToCsvListExtensions.ToDistinctOrderedCsvList(List`1 programIndices) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\ProjectFirma.Web\Common\ToCsvListExtensions.cs:line 24
   at ASP._Page_Views_Agreement_Detail_cshtml.Execute() in c:\sitka\WADNRForestHealth\wwwroot\Views\Agreement\Detail.cshtml:line 182
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.StartPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)