WADNR-1811 - HOTFIX: Crash on Program Delete: Fixing crash on Program Delete and improving associated messaging
* GisCrossWalkDefault needs to implement IAuditableEntity.
* GisDefaultMapping needs to implement IAuditableEntity
* Some null refs in ProgramCustomAttributeUpdate.AttributeString
* Some null refs in ProgramCustomAttributeUpdateValue.AttributeString
* Improved messaging before & after the Program Delete. It's just too significant an operation to not mention it might delete all the Projects in the system, for example.

This is a prod error from an actual user, so should be hotfixed.

2020-12-09 08:22:43,333;49;ERROR;LtInfo.Common.SitkaLogger;

Unhandled Exception:
System.NullReferenceException: GisCrossWalkDefault needs to implement IAuditableEntity
   at LtInfo.Common.DesignByContract.Check.ThrowThisException(Exception ex) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\LtInfo.Common\DesignByContract\Check.cs:line 58
   at LtInfo.Common.DesignByContract.Check.RequireNotNull(Object thisObject, String message) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\LtInfo.Common\DesignByContract\Check.cs:line 135
   at ProjectFirma.Web.Models.AuditLog.GetIAuditableEntityFromEntity(Object entity, String tableName) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\ProjectFirma.Web\Models\AuditLog.cs:line 374
   at ProjectFirma.Web.Models.AuditLog.CreateAuditLogEntryForDeleted(ObjectContext objectContext, DbEntityEntry dbEntry, String tableName, Person person, DateTime changeDate, AuditLogEventType auditLogEventType) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\ProjectFirma.Web\Models\AuditLog.cs:line 157
   at ProjectFirma.Web.Models.AuditLog.GetAuditLogRecordsForModifiedOrDeleted(DbEntityEntry dbEntry, Person person, ObjectContext objectContext) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\ProjectFirma.Web\Models\AuditLog.cs:line 99
   at ProjectFirma.Web.Models.DatabaseEntities.SaveChangesImpl(Person person, TransactionScope scope) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\ProjectFirma.Web\Models\DatabaseEntities.cs:line 81
   at ProjectFirma.Web.Models.DatabaseEntities.SaveChanges(Person userPerson) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\ProjectFirma.Web\Models\DatabaseEntities.cs:line 48
   at ProjectFirma.Web.Models.DatabaseEntities.SaveChanges(IPrincipal userPrincipal) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\ProjectFirma.Web\Models\DatabaseEntities.cs:line 41
   at ProjectFirma.Web.Common.SitkaController.OnActionExecuted(ActionExecutedContext filterContext) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\ProjectFirma.Web\Common\SitkaController.cs:line 165
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

User: Jennifer Watkins
LogonName: Jennifer.Watkins@dnr.wa.gov
PersonID: 5427
Organization: Washington State Department of Natural Resources