WA DNR FHT - changing to look for features in just the current GetExecutingAssembly() versus CurrentDomain.GetAssemblies() because we don't want to load all types from random sub-assemblies. Was causing crash in QA and Prod and not local. Using the ApprovalTests assembly brought in code from Microsoft.ReportViewer.ProcessingObjectModel
2020-12-03 17:55:26,087;57;ERROR;LtInfo.Common.SitkaLogger;

Unhandled Exception:
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at ProjectFirma.Web.Models.IRoleExtensions.<>c.<GetFeaturePermissions>b__1_0(Assembly s) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\ProjectFirma.Web\Models\IRoleExtensions.cs:line 52
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at ProjectFirma.Web.Models.IRoleExtensions.GetFeaturePermissions(IRole role, Type baseFeatureType) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\ProjectFirma.Web\Models\IRoleExtensions.cs:line 53
   at ProjectFirma.Web.Models.Role.GetFeaturePermissions() in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\ProjectFirma.Web\Models\Role.cs:line 35
   at ProjectFirma.Web.Views.Role.DetailViewData..ctor(Person currentPerson, IRole role) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\ProjectFirma.Web\Views\Role\DetailViewData.cs:line 46
   at ProjectFirma.Web.Controllers.RoleController.ViewDetail(IRole role) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\ProjectFirma.Web\Controllers\RoleController.cs:line 81
   at ProjectFirma.Web.Controllers.RoleController.Detail(Int32 roleID) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\ProjectFirma.Web\Controllers\RoleController.cs:line 76
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)Could not load file or assembly 'Microsoft.ReportViewer.ProcessingObjectModel, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
Fusion Log:
WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

Could not load file or assembly 'Microsoft.ReportViewer.ProcessingObjectModel, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
Fusion Log:
WRN: Assembly binding logging is turned OFF.