WADNR: Fixing crash:
I am assuming FirmPage is a little blob of dynamic content that we can inject on to the page, yes?

2019-03-25 12:35:52,999;8;ERROR;LtInfo.Common.SitkaLogger;

Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at LtInfo.Common.DesignByContract.Check.ThrowThisException(Exception ex) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\LtInfo.Common\DesignByContract\Check.cs:line 58
   at LtInfo.Common.DesignByContract.Check.RequireNotNull(Object thisObject) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\LtInfo.Common\DesignByContract\Check.cs:line 127
   at ProjectFirma.Web.Models.FirmaPage.GetFirmaPageByPageType(FirmaPageType firmaPageType) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\ProjectFirma.Web\Models\FirmaPage.cs:line 36
   at ProjectFirma.Web.Controllers.GrantController.Index() in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\ProjectFirma.Web\Controllers\GrantController.cs:line 340
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

User: Anonymous

IP Address: 192.168.10.203
Hostname: brian.sitka.local
Whois Info:
            NetRange:       192.168.0.0 - 192.168.255.255
            CIDR:           192.168.0.0/16
            NetName:        PRIVATE-ADDRESS-CBLK-RFC1918-IANA-RESERVED
            NetHandle:      NET-192-168-0-0-1
            Parent:         NET192 (NET-192-0-0-0-0)
            NetType:        IANA Special Use
            OriginAS:
            Organization:   Internet Assigned Numbers Authority (IANA)
            RegDate:        1994-03-15
            Updated:        2013-08-30
            Comment:        These addresses are in use by many millions of independently operated networks, which might be as small as a single computer connected to a home gateway, and are automatically configured in hundreds of millions of devices.  They are only intended for use within a private context  and traffic that needs to cross the Internet will need to use a different, unique address.
            Comment:
            Comment:        These addresses can be used by anyone without any need to coordinate with IANA or an Internet registry.  The traffic from these addresses does not come from ICANN or IANA.  We are not the source of activity you may see on logs or in e-mail records.  Please refer to http://www.iana.org/abuse/answers
            Comment:
            Comment:        These addresses were assigned by the IETF, the organization that develops Internet protocols, in the Best Current Practice document, RFC 1918 which can be found at:
            Comment:        http://datatracker.ietf.org/doc/rfc1918
            Ref:            https://rdap.arin.net/registry/ip/192.168.0.0
            OrgName:        Internet Assigned Numbers Authority
            OrgId:          IANA
            Address:        12025 Waterfront Drive
            Address:        Suite 300
            City:           Los Angeles
            StateProv:      CA
            PostalCode:     90292
            Country:        US
            RegDate:
            Updated:        2012-08-31
            Ref:            https://rdap.arin.net/registry/entity/IANA
            OrgTechHandle: IANA-IP-ARIN
            OrgTechName:   ICANN
            OrgTechPhone:  +1-310-301-5820
            OrgTechEmail:  abuse@iana.org
            OrgTechRef:    https://rdap.arin.net/registry/entity/IANA-IP-ARIN
            OrgAbuseHandle: IANA-IP-ARIN
            OrgAbuseName:   ICANN
            OrgAbusePhone:  +1-310-301-5820
            OrgAbuseEmail:  abuse@iana.org
            OrgAbuseRef:    https://rdap.arin.net/registry/entity/IANA-IP-ARIN

URL: https://wadnrforesthealth.qa.projectfirma.com/Grant/Index

Http Request:
GET /Grant/Index HTTP/1.1
Connection: close
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cookie: _ga=GA1.2.207795324.1551384976; _gid=GA1.2.1682917140.1553541260; ASP.NET_SessionId=tioqxs3pcst24wxaxjb05qct; _gat=1
Host: wadnrforesthealth.qa.projectfirma.com
Referer: https://wadnrforesthealth.qa.projectfirma.com/FundingSource/Index
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
upgrade-insecure-requests: 1

System.NullReferenceException: Object reference not set to an instance of an object.
   at LtInfo.Common.DesignByContract.Check.ThrowThisException(Exception ex) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\LtInfo.Common\DesignByContract\Check.cs:line 58
   at LtInfo.Common.DesignByContract.Check.RequireNotNull(Object thisObject) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\LtInfo.Common\DesignByContract\Check.cs:line 127
   at ProjectFirma.Web.Models.FirmaPage.GetFirmaPageByPageType(FirmaPageType firmaPageType) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\ProjectFirma.Web\Models\FirmaPage.cs:line 36
   at ProjectFirma.Web.Controllers.GrantController.Index() in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\ProjectFirma.Web\Controllers\GrantController.cs:line 340
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)