WADNR: I believe this likely fixes the error, but am not 100% sure.
From: Application Alerts WA DNR Forest Health Tracker <appalerts-wadnrforesthealthtracker@sitkatech.com>
Sent: Thursday, April 11, 2019 9:47 AM
To: Application Alerts WA DNR Forest Health Tracker <appalerts-wadnrforesthealthtracker@sitkatech.com>
Subject: WADNRForestHealth Alert: qa application error /Organization/Detail/4708 ArgumentException

2019-04-11 09:46:31,056;40;ERROR;LtInfo.Common.SitkaLogger;

Unhandled Exception:
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at ProjectFirma.Web.Models.DatabaseContextExtensions.GetFullCategoryYearDictionary(IEnumerable`1 projectGrantAllocationExpenditures, Func`2 filterFunction, List`1 filterValues, Func`2 sortFunction, List`1 rangeOfYears) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\ProjectFirma.Web\Models\ProjectGrantAllocationExpenditure.DatabaseContextExtensions.cs:line 100
   at ProjectFirma.Web.Models.DatabaseContextExtensions.ToGoogleChart(IEnumerable`1 projectGrantAllocationExpenditures, Func`2 filterFunction, List`1 filterValues, Func`2 sortFunction, List`1 rangeOfYears, String chartContainerID, String chartTitle, GoogleChartType googleChartType, Boolean isStacked) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\ProjectFirma.Web\Models\ProjectGrantAllocationExpenditure.DatabaseContextExtensions.cs:line 80
   at ProjectFirma.Web.Controllers.OrganizationController.GetCalendarYearExpendituresFromOrganizationGrantAllocationsLineChartViewData(Organization organization) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\ProjectFirma.Web\Controllers\OrganizationController.cs:line 214
   at ProjectFirma.Web.Controllers.OrganizationController.Detail(OrganizationPrimaryKey organizationPrimaryKey) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\ProjectFirma.Web\Controllers\OrganizationController.cs:line 138
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

User: Andy Tate
LogonName: Andy.Tate@dnr.wa.gov
PersonID: 5250
Organization: Washington State Department of Natural Resources

IP Address: 146.76.42.89
Hostname: 146.76.42.89
Whois Info:
            NetRange:       146.76.0.0 - 146.76.255.255
            CIDR:           146.76.0.0/16
            NetName:        DNRGISNET
            NetHandle:      NET-146-76-0-0-1
            Parent:         NET146 (NET-146-0-0-0-0)
            NetType:        Direct Assignment
            OriginAS:
            Organization:   Washington State Department of Natural Resources (WSDNR)
            RegDate:        1991-01-23
            Updated:        2010-03-12
            Ref:            https://rdap.arin.net/registry/ip/146.76.0.0
            OrgName:        Washington State Department of Natural Resources
            OrgId:          WSDNR
            Address:        Information Technology Division, 1111 Washington Street SE; 3rd Floor E
            City:           Olympia
            StateProv:      WA
            PostalCode:     98504-7020
            Country:        US
            RegDate:        1991-01-23
            Updated:        2011-09-24
            Ref:            https://rdap.arin.net/registry/entity/WSDNR
            OrgAbuseHandle: DAMMA-ARIN
            OrgAbuseName:   Damm, Anton
            OrgAbusePhone:  +1-360-902-1500
            OrgAbuseEmail:  dnrresysadmin@dnr.wa.gov
            OrgAbuseRef:    https://rdap.arin.net/registry/entity/DAMMA-ARIN
            OrgTechHandle: DAMMA-ARIN
            OrgTechName:   Damm, Anton
            OrgTechPhone:  +1-360-902-1500
            OrgTechEmail:  dnrresysadmin@dnr.wa.gov
            OrgTechRef:    https://rdap.arin.net/registry/entity/DAMMA-ARIN

URL: https://wadnrforesthealth.qa.projectfirma.com/Organization/Detail/4708

Http Request:
GET /Organization/Detail/4708 HTTP/1.1
Connection: close
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cookie: _ga=GA1.2.1732082288.1553029396; ASP.NET_SessionId=d2dnsp4aynsth0uw1w35utyz; grid_ck_dhtmlinteractionEventsGridNamefilterVisible=0; grid_ck_dhtmluserInteractionEventsFromUserGridfilterVisible=0; grid_ck_dhtmluserProjectListGridfilterVisible=0; grid_ck_dhtmluserNotificationsfilterVisible=0; grid_ck_dhtmlgrantAllocationsNoDataGridNamefilterVisible=0; WashingtonDNRForestHealthTrackerIdentity=T4IweATS6970inWden3msQ6KLNbKtm9iaR-Ed6g_C3c-uUiQn5AxBkX65B2nJ452ptPHKJlryBXUNX1cy-KULyy308MUpTSrJnt0HhaaOkIKgR9GGkNGqXaeGEFPpFEdFIaolSHetMT0Dt2fiTx-_jemnsfqNfVYomZY6Kd0w_NtibJx455Gp16q4DXQRRJm_ySTkglfxILxNM4WxlWs42eLX3Qn_PgUnRF2Ihuzg90; grid_ck_dhtmlinvoiceLineItemGridfilterVisible=0; _gid=GA1.2.671829622.1554908360; grid_ck_dhtmlprojectOrganizationsFromOrganizationGridfilterVisible=0; grid_ck_dhtmlproposalsGridfilterVisible=0; grid_ck_dhtmlpendingProjectsGridfilterVisible=0; grid_ck_dhtmlprojectCalendarYearExpendituresForOrganizationGridfilterVisible=0; grid_ck_dhtmlagreementPersonGridfilterVisible=0; grid_ck_dhtmlprojectUpdateBatchfilterVisible=0; grid_ck_dhtmlprojectNotificationsfilterVisible=0; grid_ck_dhtmlprojectInteractionEventsGridfilterVisible=0; grid_ck_dhtmlprojectsCalendarYearExpendituresFromGrantAllocationGridfilterVisible=0; grid_ck_dhtmlprojectsGrantAllocationRequestsFromGrantAllocationGridfilterVisible=0; grid_ck_dhtmlgrantsGridName=%7C%7C%7C2019-DG-11062765-722%7C%7C%7C%7C%7C%7C%7C; grid_ck_dhtmlUserGrid=%7Clam%7C%7C%7C%7C%7C%7C%7C%7C%7C%7C%7C%7C; grid_ck_dhtmlgrantAllocationsGridName=%7C2011-DG-11062764-015%7C%7C%7C%7C%7C%7C%7C%7C%7C%7C%7C%7C%7C; _gat_gtag_UA_134842201_1=1; grid_ck_dhtmluserAgreementsFromUserGridfilterVisible=0
Host: wadnrforesthealth.qa.projectfirma.com
Referer: https://wadnrforesthealth.qa.projectfirma.com/GrantAllocation/GrantAllocationDetail/119
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
upgrade-insecure-requests: 1

System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at ProjectFirma.Web.Models.DatabaseContextExtensions.GetFullCategoryYearDictionary(IEnumerable`1 projectGrantAllocationExpenditures, Func`2 filterFunction, List`1 filterValues, Func`2 sortFunction, List`1 rangeOfYears) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\ProjectFirma.Web\Models\ProjectGrantAllocationExpenditure.DatabaseContextExtensions.cs:line 100
   at ProjectFirma.Web.Models.DatabaseContextExtensions.ToGoogleChart(IEnumerable`1 projectGrantAllocationExpenditures, Func`2 filterFunction, List`1 filterValues, Func`2 sortFunction, List`1 rangeOfYears, String chartContainerID, String chartTitle, GoogleChartType googleChartType, Boolean isStacked) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\ProjectFirma.Web\Models\ProjectGrantAllocationExpenditure.DatabaseContextExtensions.cs:line 80
   at ProjectFirma.Web.Controllers.OrganizationController.GetCalendarYearExpendituresFromOrganizationGrantAllocationsLineChartViewData(Organization organization) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\ProjectFirma.Web\Controllers\OrganizationController.cs:line 214
   at ProjectFirma.Web.Controllers.OrganizationController.Detail(OrganizationPrimaryKey organizationPrimaryKey) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\ProjectFirma.Web\Controllers\OrganizationController.cs:line 138
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)