WADNR - Fixing issue with GDB upload. Need to MakeValid a bit more aggressively. Improving comment a bit. 2019-02-20 07:53:27,221;48;ERROR;LtInfo.Common.SitkaLogger;
Unhandled Exception:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: 24144: This operation cannot be completed because the instance is not valid. Use MakeValid to convert the instance to a valid instance. Note that MakeValid may cause the points of a geometry instance to shift slightly.
   at Microsoft.SqlServer.Types.SqlGeometry.ThrowIfInvalid()
   at Microsoft.SqlServer.Types.SqlGeometry.STCentroid()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Data.Entity.SqlServer.SqlSpatialServices.GetCentroid(DbGeometry geometryValue)
   at LtInfo.Common.DbSpatial.DbSpatialHelper.GetRepresentativeXCoordinate(DbGeometry geometry) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\LtInfo.Common\DbSpatial\DbSpatialHelper.cs:line 77
   at LtInfo.Common.DbSpatial.DbSpatialHelper.FeetToLonDegree(DbGeometry geometry, Double feet) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\LtInfo.Common\DbSpatial\DbSpatialHelper.cs:line 57
   at LtInfo.Common.DbSpatial.DbSpatialHelper.FeetToAverageLatLonDegree(DbGeometry geometry, Double feet) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\LtInfo.Common\DbSpatial\DbSpatialHelper.cs:line 37
   at LtInfo.Common.DbSpatial.DbSpatialHelper.Reduce(List`1 geometries) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\LtInfo.Common\DbSpatial\DbSpatialHelper.cs:line 113
   at ProjectFirma.Web.Controllers.ProjectCreateController.ApproveGisUpload(ProjectPrimaryKey projectPrimaryKey, ProjectLocationDetailViewModel viewModel) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\ProjectFirma.Web\Controllers\ProjectCreateController.cs:line 808
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

User: Andy Tate
LogonName: Andy.Tate@dnr.wa.gov
PersonID: 5250
Organization: Washington State Department of Natural Resources

IP Address: 146.76.42.125
Hostname: 146.76.42.125
Whois Info:
            NetRange:       146.76.0.0 - 146.76.255.255
            CIDR:           146.76.0.0/16
            NetName:        DNRGISNET
            NetHandle:      NET-146-76-0-0-1
            Parent:         NET146 (NET-146-0-0-0-0)
            NetType:        Direct Assignment
            OriginAS:
            Organization:   Washington State Department of Natural Resources (WSDNR)
            RegDate:        1991-01-23
            Updated:        2010-03-12
            Ref:            https://rdap.arin.net/registry/ip/146.76.0.0
            OrgName:        Washington State Department of Natural Resources
            OrgId:          WSDNR
            Address:        Information Technology Division, 1111 Washington Street SE; 3rd Floor E
            City:           Olympia
            StateProv:      WA
            PostalCode:     98504-7020
            Country:        US
            RegDate:        1991-01-23
            Updated:        2011-09-24
            Ref:            https://rdap.arin.net/registry/entity/WSDNR
            OrgTechHandle: DAMMA-ARIN
            OrgTechName:   Damm, Anton
            OrgTechPhone:  +1-360-902-1500
            OrgTechEmail:  dnrresysadmin@dnr.wa.gov
            OrgTechRef:    https://rdap.arin.net/registry/entity/DAMMA-ARIN
            OrgAbuseHandle: DAMMA-ARIN
            OrgAbuseName:   Damm, Anton
            OrgAbusePhone:  +1-360-902-1500
            OrgAbuseEmail:  dnrresysadmin@dnr.wa.gov
            OrgAbuseRef:    https://rdap.arin.net/registry/entity/DAMMA-ARIN

URL: https://wadnrforesthealth.qa.projectfirma.com/ProjectCreate/ApproveGisUpload/12616

Http Request:
POST /ProjectCreate/ApproveGisUpload/12616 HTTP/1.1
Connection: close
Content-Length: 6137269
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cookie: ASP.NET_SessionId=ahmdbzqebgksy0iuo35qm1vd; grid_ck_dhtmlprojectOrganizationsFromOrganizationGridfilterVisible=0; grid_ck_dhtmlagreementOrganizationsFromOrganizationGridfilterVisible=0; grid_ck_dhtmlprojectCalendarYearExpendituresForOrganizationGridfilterVisible=0; grid_ck_dhtmlprojectUpdateBatchfilterVisible=0; grid_ck_dhtmlprojectNotificationsfilterVisible=0; grid_ck_dhtmlProjectFocusAreaGridfilterVisible=0; grid_ck_dhtmlgrantsGridName=%7C%7C%7C16-DG-11062765-731%7C%7C%7C%7C%7C%7C%7C; grid_ck_dhtmlagreementPersonGridfilterVisible=0; grid_ck_dhtmluserNotificationsfilterVisible=0; .AspNet.ApplicationCookie=M9oDeCEbLO36YVWTKAen8hKxBt9LLCW6exDmmwQKL5sFTTLSrSIqWTK0ykYQLr4KhCjFIG47BbAcltjbJC_e1P3GbM5eKbDPYgOnow8swZwTjZ4WRIrG32y94VEJqGztpIzRyMWvtsRmjIhyxUCjGh4Mo7NkYsHj6sCV0zn88237-F8arkYsCV8qWnUvA5dP1iMhbtoUPzaFuBPseIaBtoq_OI6G7Az4Jn1QrJ0nc4kfQ4jC1WQDc7r1C5HxnhA7i196hbiH5YoNt79aQ2KhJphH4xb1IE0QZimXNv8FkojoXg_Nng3jVa8KWdZIHl55yulyh8sPrZzMgJcZJFyedDQ0Tf3j3EgVWCqT8zm7oFqDcz2TcM4614tLZaImLIhz6bIlR7dFANWe2F-OxGbJW30E_Mj6ejjE7az8ozes7G4DODyEpf3d624hRwd5BcfFKf7pU94UXxekAIG6vKM9XP6NwjamysL17KpPBwphiuQ; grid_ck_dhtmlgrantAllocationsNoDataGridNamefilterVisible=0; grid_ck_dhtmlgrantAllocationsGridName=%7C2010-DG-11062764-010%7C%7C%7C%7C%7C%7C%7C%7C%7C%7C%7C%7C; grid_ck_dhtmlproposalsGridfilterVisible=0; grid_ck_dhtmlpendingProjectsGridfilterVisible=0; grid_ck_dhtmluserProjectListGridfilterVisible=0; grid_ck_dhtmluserAgreementsFromUserGridfilterVisible=0; gridSettingsUserGridDivID=||1-asc||; gridSettingstreatmentActivtiesGridDivID=150-150-150-120-75-75-75-125-125-75-75-75-75-75-75-75-75-75-75-75-75-75-75-200|150-150-150-125-75-75-75-125-125-75-75-75-75-75-75-75-75-75-75-75-75-75-75-200|||; gridSettingsagreementsGridNameDivID=0-30-30-70-100-118-148-180-120-120-70|0-30-30-70-100-130-130-180-120-120-70|||; grid_ck_dhtmlagreementsGridName=%7C%7C%7C%7C%7C%7C%7C%7C%7C%7C
Host: wadnrforesthealth.qa.projectfirma.com
Referer: https://wadnrforesthealth.qa.projectfirma.com/ProjectCreate/EditLocationDetailed/12616
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36
origin: https://wadnrforesthealth.qa.projectfirma.com
x-requested-with: XMLHttpRequest

ProjectLocationJsons%5B0%5D.ProjectLocationGeometryWellKnownText=POLYGON+((-121.05388000125657+47.436732999349125%2C+-121.05403300243253+47.436737999751905%2C+-121.05416400016935+47.43678600036463%2C+-121.05430000084611+47.436829999621466%2C+-121.05429000104834+47.43696499940187%2C+-121.05420900260054+47.43706700057222%2C+-121.05415000138369+47.437198000222914%2C+-121.0540640019116+47.43728399967666%2C+-121.05390000270559

(ETc.)