WADNR FHT: Fixing following crash:
2019-07-31 13:56:37,798;3;ERROR;LtInfo.Common.SitkaLogger;

Unhandled Exception:
System.NullReferenceException: GrantAllocationChangeLog needs to implement IAuditableEntity
   at LtInfo.Common.DesignByContract.Check.ThrowThisException(Exception ex) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\LtInfo.Common\DesignByContract\Check.cs:line 58
   at LtInfo.Common.DesignByContract.Check.RequireNotNull(Object thisObject, String message) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\LtInfo.Common\DesignByContract\Check.cs:line 135
   at ProjectFirma.Web.Models.AuditLog.GetIAuditableEntityFromEntity(Object entity, String tableName) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\ProjectFirma.Web\Models\AuditLog.cs:line 374
   at ProjectFirma.Web.Models.AuditLog.CreateAuditLogEntryForDeleted(ObjectContext objectContext, DbEntityEntry dbEntry, String tableName, Person person, DateTime changeDate, AuditLogEventType auditLogEventType) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\ProjectFirma.Web\Models\AuditLog.cs:line 157
   at ProjectFirma.Web.Models.AuditLog.GetAuditLogRecordsForModifiedOrDeleted(DbEntityEntry dbEntry, Person person, ObjectContext objectContext) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\ProjectFirma.Web\Models\AuditLog.cs:line 99
   at ProjectFirma.Web.Models.DatabaseEntities.SaveChangesImpl(Person person, TransactionScope scope) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\ProjectFirma.Web\Models\DatabaseEntities.cs:line 79
   at ProjectFirma.Web.Models.DatabaseEntities.SaveChanges(Person userPerson) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\ProjectFirma.Web\Models\DatabaseEntities.cs:line 46
   at ProjectFirma.Web.Models.DatabaseEntities.SaveChanges(IPrincipal userPrincipal) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\ProjectFirma.Web\Models\DatabaseEntities.cs:line 39
   at ProjectFirma.Web.Common.SitkaController.OnActionExecuted(ActionExecutedContext filterContext) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\ProjectFirma.Web\Common\SitkaController.cs:line 164
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

User: Sydney Debien
LogonName: Sydney.Debien@dnr.wa.gov
PersonID: 5413
Organization: Washington State Department of Natural Resources

IP Address: 146.76.42.160
Hostname: 146.76.42.160
Whois Info:
            NetRange:       146.76.0.0 - 146.76.255.255
            CIDR:           146.76.0.0/16
            NetName:        DNRGISNET
            NetHandle:      NET-146-76-0-0-1
            Parent:         NET146 (NET-146-0-0-0-0)
            NetType:        Direct Assignment
            OriginAS:
            Organization:   Washington State Department of Natural Resources (WSDNR)
            RegDate:        1991-01-23
            Updated:        2010-03-12
            Ref:            https://rdap.arin.net/registry/ip/146.76.0.0
            OrgName:        Washington State Department of Natural Resources
            OrgId:          WSDNR
            Address:        Information Technology Division, 1111 Washington Street SE; 3rd Floor E
            City:           Olympia
            StateProv:      WA
            PostalCode:     98504-7020
            Country:        US
            RegDate:        1991-01-23
            Updated:        2011-09-24
            Ref:            https://rdap.arin.net/registry/entity/WSDNR
            OrgAbuseHandle: DAMMA-ARIN
            OrgAbuseName:   Damm, Anton
            OrgAbusePhone:  +1-360-902-1500
            OrgAbuseEmail:  dnrresysadmin@dnr.wa.gov
            OrgAbuseRef:    https://rdap.arin.net/registry/entity/DAMMA-ARIN
            OrgTechHandle: DAMMA-ARIN
            OrgTechName:   Damm, Anton
            OrgTechPhone:  +1-360-902-1500
            OrgTechEmail:  dnrresysadmin@dnr.wa.gov
            OrgTechRef:    https://rdap.arin.net/registry/entity/DAMMA-ARIN

URL: https://foresthealthtracker.dnr.wa.gov/GrantAllocation/DeleteGrantAllocation/291

Http Request:
POST /GrantAllocation/DeleteGrantAllocation/291 HTTP/1.1
Connection: close
Content-Length: 0
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cookie: _ga=GA1.2.86635262.1559592957; ASP.NET_SessionId=rygb434cgpl2r5ceery4igqh; _gid=GA1.2.850709591.1564601880; WashingtonDNRForestHealthTrackerIdentity=SdrpAcdjspQWayKRJHngCyiIiX5Yi2CZ1JkzxNEmWdXUwcbBWwap1C1joHPnjyFk9Cc97jJY0A-nIeTR87JZG_L79aMkW7ez5pvdRlBky23BXuIWa1EQtjcU2HdhWnj3oNjKpUXrBMERWkBDT9hnVYYd1KL-9blWhaIAJBYHjrKrAbdrmHb5Ev2_g0pEKxFBf5zafQq4hEIaqxbXTUUHUOve_PFP3fV74F9Qucr1ZCyuuJsqDJV4v1amdkqX1l9c; grid_ck_dhtmlgrantAllocationsNoDataGridNamefilterVisible=0; gridSettingsgrantsGridNameDivID=0-30-30-140-90-305-90-90-90-90-90-90|0-30-30-140-90-250-90-90-90-90-90-90|3-des||; grid_ck_dhtmlgrantModificationsGridNamefilterVisible=0; grid_ck_dhtmlgrantAllocationsGridNamefilterVisible=0
Host: foresthealthtracker.dnr.wa.gov
Referer: https://foresthealthtracker.dnr.wa.gov/Grant/GrantDetail/27
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
origin: https://foresthealthtracker.dnr.wa.gov
x-requested-with: XMLHttpRequest

System.NullReferenceException: GrantAllocationChangeLog needs to implement IAuditableEntity
   at LtInfo.Common.DesignByContract.Check.ThrowThisException(Exception ex) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\LtInfo.Common\DesignByContract\Check.cs:line 58
   at LtInfo.Common.DesignByContract.Check.RequireNotNull(Object thisObject, String message) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\LtInfo.Common\DesignByContract\Check.cs:line 135
   at ProjectFirma.Web.Models.AuditLog.GetIAuditableEntityFromEntity(Object entity, String tableName) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\ProjectFirma.Web\Models\AuditLog.cs:line 374
   at ProjectFirma.Web.Models.AuditLog.CreateAuditLogEntryForDeleted(ObjectContext objectContext, DbEntityEntry dbEntry, String tableName, Person person, DateTime changeDate, AuditLogEventType auditLogEventType) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\ProjectFirma.Web\Models\AuditLog.cs:line 157
   at ProjectFirma.Web.Models.AuditLog.GetAuditLogRecordsForModifiedOrDeleted(DbEntityEntry dbEntry, Person person, ObjectContext objectContext) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\ProjectFirma.Web\Models\AuditLog.cs:line 99
   at ProjectFirma.Web.Models.DatabaseEntities.SaveChangesImpl(Person person, TransactionScope scope) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\ProjectFirma.Web\Models\DatabaseEntities.cs:line 79
   at ProjectFirma.Web.Models.DatabaseEntities.SaveChanges(Person userPerson) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\ProjectFirma.Web\Models\DatabaseEntities.cs:line 46
   at ProjectFirma.Web.Models.DatabaseEntities.SaveChanges(IPrincipal userPrincipal) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\ProjectFirma.Web\Models\DatabaseEntities.cs:line 39
   at ProjectFirma.Web.Common.SitkaController.OnActionExecuted(ActionExecutedContext filterContext) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\ProjectFirma.Web\Common\SitkaController.cs:line 164
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)