WADNR - Fixing Fact Sheet crash observed in prod, triggered by Google crawler. 2019-02-20 13:38:33,529;22;ERROR;LtInfo.Common.SitkaLogger;
Unhandled Exception:
LtInfo.Common.DesignByContract.AssertionException: There is no Fact Sheet available for this Project because it has been terminated.
   at LtInfo.Common.DesignByContract.Check.ThrowThisException(Exception ex) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\LtInfo.Common\DesignByContract\Check.cs:line 58
   at LtInfo.Common.DesignByContract.Check.Assert(Boolean assertion, String message) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\LtInfo.Common\DesignByContract\Check.cs:line 369
   at ProjectFirma.Web.Controllers.ProjectController.FactSheet(ProjectPrimaryKey projectPrimaryKey) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\ProjectFirma.Web\Controllers\ProjectController.cs:line 335
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

User: Anonymous

IP Address: 66.249.75.157
Hostname: crawl-66-249-75-157.googlebot.com Whois Info:
            NetRange:       66.249.64.0 - 66.249.95.255
            CIDR:           66.249.64.0/19
            NetName:        GOOGLE
            NetHandle:      NET-66-249-64-0-1
            Parent:         NET66 (NET-66-0-0-0-0)
            NetType:        Direct Allocation
            OriginAS:
            Organization:   Google LLC (GOGL)
            RegDate:        2004-03-05
            Updated:        2012-02-24
            Ref:            https://rdap.arin.net/registry/ip/66.249.64.0
            OrgName:        Google LLC
            OrgId:          GOGL
            Address:        1600 Amphitheatre Parkway
            City:           Mountain View
            StateProv:      CA
            PostalCode:     94043
            Country:        US
            RegDate:        2000-03-30
            Updated:        2018-10-24
            Comment:        Please note that the recommended way to file abuse complaints are located in the following links.
            Comment:
            Comment:        To report abuse and illegal activity: https://www.google.com/contact/
            Comment:
            Comment:        For legal requests: http://support.google.com/legal
            Comment:
            Comment:        Regards,
            Comment:        The Google Team
            Ref:            https://rdap.arin.net/registry/entity/GOGL
            OrgAbuseHandle: ABUSE5250-ARIN
            OrgAbuseName:   Abuse
            OrgAbusePhone:  +1-650-253-0000
            OrgAbuseEmail:  network-abuse@google.com
            OrgAbuseRef:    https://rdap.arin.net/registry/entity/ABUSE5250-ARIN
            OrgTechHandle: ZG39-ARIN
            OrgTechName:   Google LLC
            OrgTechPhone:  +1-650-253-0000
            OrgTechEmail:  arin-contact@google.com
            OrgTechRef:    https://rdap.arin.net/registry/entity/ZG39-ARIN

URL: https://foresthealthtracker.dnr.wa.gov/Project/FactSheet/12554

Http Request:
GET /Project/FactSheet/12554 HTTP/1.1
Connection: keep-alive
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip,deflate,br
From: googlebot(at)googlebot.com
Host: foresthealthtracker.dnr.wa.gov
User-Agent: Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)

LtInfo.Common.DesignByContract.AssertionException: There is no Fact Sheet available for this Project because it has been terminated.
   at LtInfo.Common.DesignByContract.Check.ThrowThisException(Exception ex) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\LtInfo.Common\DesignByContract\Check.cs:line 58
   at LtInfo.Common.DesignByContract.Check.Assert(Boolean assertion, String message) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\LtInfo.Common\DesignByContract\Check.cs:line 369
   at ProjectFirma.Web.Controllers.ProjectController.FactSheet(ProjectPrimaryKey projectPrimaryKey) in C:\Sitka\WADNRForestHealth\Temp\build\WADNRForestHealthTrunk\WADNRForestHealth\Source\ProjectFirma.Web\Controllers\ProjectController.cs:line 335
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)